name: trendix
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  webview_flutter: ^4.4.2
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
